"""fix some bugs that occured in UserBook model

Revision ID: 04164c9c176e
Revises: ddcc813356d0
Create Date: 2026-02-17 11:51:10.585933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04164c9c176e'
down_revision: Union[str, Sequence[str], None] = 'ddcc813356d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
