"""change user_book model to class Model

Revision ID: 58ca206f09dc
Revises: 7cb2b807136d
Create Date: 2026-02-17 11:02:01.571572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58ca206f09dc'
down_revision: Union[str, Sequence[str], None] = '7cb2b807136d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_books',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'book_id')
    )
    op.alter_column('authors', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('books', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('books', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('books', 'stock',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('books', 'rating_avg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('books', 'rating_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('books', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('books', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('books', 'rating_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('books', 'rating_avg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('books', 'stock',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('books', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('books', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('authors', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('users_books')
    # ### end Alembic commands ###
