"""change one to many to many to many relationship in user and book models

Revision ID: 7cb2b807136d
Revises: 69f5aec04263
Create Date: 2026-02-10 13:58:12.222140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cb2b807136d'
down_revision: Union[str, Sequence[str], None] = '69f5aec04263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('books_user_id_fkey'), 'books', type_='foreignkey')
    op.drop_column('books', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('books_user_id_fkey'), 'books', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
